### ISSUE TITLE
Getting the tsv

### ISSUE THREAD

**Issue by seiyria** [nahog/freestyle-libre-parser-viewer#4]
Hey! Nice project you have here. I was wondering how you get the tsv data off of the libre for use with this?

**Comment by stuzog** [comment]
Install the Freestyle Libre software on your computer; connect the reader via the supplied MicroUSB -> USB cable (which should crank up the Libre Software if it isn't already running); then select File -> Export Data, which will upload a CSV file to the destination of your choice on your drive.

**Comment by seiyria** [comment]
Ah, thank you!
